// Copies contract ABIs from the Foundry build into lib/abi, so the site always talks to exactly the code in
// contracts/src. Run after `forge build`: npm run abi
import { readFileSync, writeFileSync } from 'node:fs';

for (const name of ['LadderVault', 'CohortMarket', 'LadderGovernor']) {
  const { abi } = JSON.parse(readFileSync(`contracts/out/${name}.sol/${name}.json`, 'utf8'));
  writeFileSync(`lib/abi/${name}.js`, `// Generated by scripts/export-abi.mjs from contracts/out. Do not edit.\nexport default ${JSON.stringify(abi, null, 2)};\n`);
  console.log(`lib/abi/${name}.js: ${abi.length} entries`);
}
